-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gmailEmail" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gmailRefreshToken" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gmailAccessToken" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gmailTokenExpiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gmailConnectedAt" TIMESTAMP(3);
